sudo: false
language: python
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
python:
  - "3.7"
  - "3.8"
  - "pypy3"
addons:
  apt:
    packages:
        libcups2-dev
install: pip install tox-travis
script: tox -v
